// src/App.tsx

import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route, Link, useLocation } from "react-router-dom";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu"
import { Settings, User, ChevronDown, LogOut } from "lucide-react";
import Home from "./pages/Home";
import ResumeBuilder from "./pages/ResumeBuilder";
import NotFound from "./pages/NotFound";
import { useEffect, useState } from "react";

const queryClient = new QueryClient();

const NavLink = ({ to, children }: { to: string; children: React.ReactNode }) => {
  const location = useLocation();
  const isActive = location.pathname === to;
  
  return (
    <Link 
      to={to} 
      className={`relative h-14 flex items-center px-4 text-sm font-medium transition-colors hover:text-white ${
        isActive 
          ? "text-white after:absolute after:bottom-[-1px] after:left-0 after:right-0 after:h-0.5 after:bg-white" 
          : "text-white/80 hover:after:absolute hover:after:bottom-[-1px] hover:after:left-0 hover:after:right-0 hover:after:h-0.5 hover:after:bg-white/50"
      }`}
    >
      {children}
    </Link>
  );
};

const ProfileDropdown = () => {
  const location = useLocation();
  
  return (
    <DropdownMenu>
      <DropdownMenuTrigger className="flex items-center gap-2 px-4 h-14 text-sm font-medium text-white/80 hover:text-white">
        <User className="h-4 w-4" />
        <span>Profile</span>
        <ChevronDown className="h-4 w-4" />
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-48">
        <Link to="/profile">
          <DropdownMenuItem className="cursor-pointer">
            <User className="h-4 w-4 mr-2" />
            Profile
          </DropdownMenuItem>
        </Link>
        <Link to="/settings">
          <DropdownMenuItem className="cursor-pointer">
            <Settings className="h-4 w-4 mr-2" />
            Settings
          </DropdownMenuItem>
        </Link>
        <DropdownMenuSeparator />
        <DropdownMenuItem className="cursor-pointer text-red-600">
          <LogOut className="h-4 w-4 mr-2" />
          Sign out
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

const Navigation = ({ isPublicView }: { isPublicView: boolean }) => {
  if (isPublicView) return null;

  return (
    <nav className="bg-[#377E7F]">
      <div className="max-w-7xl mx-auto px-4 flex items-center justify-between h-14">
        <Link to="/">
          <img 
            src="/lovable-uploads/b319e0ed-4a1d-4f33-a859-c9ab1db0a991.png" 
            alt="Accomplish It" 
            className="h-6"
          />
        </Link>
        <NavigationMenu className="absolute left-1/2 -translate-x-1/2">
          <NavigationMenuList className="space-x-2">
            <NavigationMenuItem>
              <NavLink to="/">
                Accomplishments
              </NavLink>
            </NavigationMenuItem>
            <NavigationMenuItem>
              <NavLink to="/resume-builder">
                Artifacts
              </NavLink>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>
        <ProfileDropdown />
      </div>
    </nav>
  );
};

const App = () => {
  const [isPublicView, setIsPublicView] = useState(false);

  useEffect(() => {
    const handleStorageChange = () => {
      const view = localStorage.getItem('view');
      setIsPublicView(view === 'public');
    };

    handleStorageChange();
    window.addEventListener('storage', handleStorageChange);
    window.addEventListener('viewChange', handleStorageChange);

    return () => {
      window.removeEventListener('storage', handleStorageChange);
      window.removeEventListener('viewChange', handleStorageChange);
    };
  }, []);

  return (
    <QueryClientProvider client={queryClient}>
      <TooltipProvider>
        <Toaster />
        <Sonner />
        <BrowserRouter>
          <Navigation isPublicView={isPublicView} />
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/resume-builder" element={<ResumeBuilder />} />
            <Route path="*" element={<NotFound />} />
          </Routes>
        </BrowserRouter>
      </TooltipProvider>
    </QueryClientProvider>
  );
};

export default App;

// src/App.vue

<template>
  <div>
    <nav v-if="!isPublicView" class="bg-[#377E7F]">
      <div class="max-w-7xl mx-auto px-4 flex items-center justify-between h-14">
        <router-link to="/">
          <img 
            src="/lovable-uploads/b319e0ed-4a1d-4f33-a859-c9ab1db0a991.png" 
            alt="Accomplish It" 
            class="h-9"
          />
        </router-link>
        
        <div class="absolute left-1/2 -translate-x-1/2">
          <nav class="space-x-2">
            <router-link 
              to="/"
              :class="[
                'relative h-14 flex items-center px-4 text-sm font-medium transition-colors hover:text-white',
                $route.path === '/' 
                  ? 'text-white after:absolute after:bottom-[-1px] after:left-0 after:right-0 after:h-0.5 after:bg-white'
                  : 'text-white/80 hover:after:absolute hover:after:bottom-[-1px] hover:after:left-0 hover:after:right-0 hover:after:h-0.5 hover:after:bg-white/50'
              ]"
            >
              Accomplishments
            </router-link>
            <router-link 
              to="/resume-builder"
              :class="[
                'relative h-14 flex items-center px-4 text-sm font-medium transition-colors hover:text-white',
                $route.path === '/resume-builder'
                  ? 'text-white after:absolute after:bottom-[-1px] after:left-0 after:right-0 after:h-0.5 after:bg-white'
                  : 'text-white/80 hover:after:absolute hover:after:bottom-[-1px] hover:after:left-0 hover:after:right-0 hover:after:h-0.5 hover:after:bg-white/50'
              ]"
            >
              Artifacts
            </router-link>
          </nav>
        </div>

        <div class="relative" v-click-outside="closeDropdown">
          <button 
            @click="toggleDropdown"
            class="flex items-center gap-2 px-4 h-14 text-sm font-medium text-white/80 hover:text-white"
          >
            <User class="h-4 w-4" />
            <span>Profile</span>
            <ChevronDown class="h-4 w-4" />
          </button>

          <div 
            v-if="isDropdownOpen"
            class="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1"
          >
            <router-link to="/profile" class="dropdown-item">
              <User class="h-4 w-4 mr-2" />
              Profile
            </router-link>
            <router-link to="/settings" class="dropdown-item">
              <Settings class="h-4 w-4 mr-2" />
              Settings
            </router-link>
            <div class="border-t my-1"></div>
            <button @click="signOut" class="dropdown-item text-red-600">
              <LogOut class="h-4 w-4 mr-2" />
              Sign out
            </button>
          </div>
        </div>
      </div>
    </nav>

    <router-view></router-view>
  </div>
</template>

<script>
import { ref, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { User, Settings, LogOut, ChevronDown } from 'lucide-vue-next'

export default {
  name: 'App',
  components: {
    User,
    Settings,
    LogOut,
    ChevronDown
  },
  setup() {
    const isPublicView = ref(false)
    const isDropdownOpen = ref(false)
    const router = useRouter()

    const toggleDropdown = () => {
      isDropdownOpen.value = !isDropdownOpen.value
    }

    const closeDropdown = () => {
      isDropdownOpen.value = false
    }

    const signOut = () => {
      closeDropdown()
    }

    const handleStorageChange = () => {
      const view = localStorage.getItem('view')
      isPublicView.value = view === 'public'
    }

    onMounted(() => {
      handleStorageChange()
      window.addEventListener('storage', handleStorageChange)
      window.addEventListener('viewChange', handleStorageChange)
    })

    onUnmounted(() => {
      window.removeEventListener('storage', handleStorageChange)
      window.removeEventListener('viewChange', handleStorageChange)
    })

    const vClickOutside = {
      mounted(el, binding) {
        el.clickOutsideEvent = (event) => {
          if (!(el === event.target || el.contains(event.target))) {
            binding.value()
          }
        }
        document.addEventListener('click', el.clickOutsideEvent)
      },
      unmounted(el) {
        document.removeEventListener('click', el.clickOutsideEvent)
      }
    }

    return {
      isPublicView,
      isDropdownOpen,
      toggleDropdown,
      closeDropdown,
      signOut,
      vClickOutside
    }
  }
}
</script>

<style scoped>
.dropdown-item {
  @apply flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 w-full text-left;
}
</style>
